base_dir: "../../datasets_FVV/N3DV/coffee_martini/frame000001"
output_dir: "results/coffee_martini_frame000001"
ext: "png"

keypoint_detector:
  num_features: 4096
  resize_to: 1024

keypoint_matcher:
  min_matches: 15
  verbose: False
  mask: False

colmap_mapper:
  max_num_models: 2
  min_model_size: 3
