base_dir: ../sony_ai/20250529/valid/lane/running

# Will be saved in ${out_dir}/${wandb.name}/${wandb.tags}.
out_dir: results
wandb:
  mode: offline
  entity: zeki31-global-page
  project: intro_cotracker
  name: lane_running
  tags:
    - imgs=all
    - tracking
    - window=15
    - glomap

retriever:
  img_dir_type: stream # images / frame / stream
  ext: jpg
  start: 0
  duration: -1
  stride: 1

  comp_ratio: 4

  pair_generator: trajectory

keypoint_detector:
  num_features: 4096
  resize_to: 1024

keypoint_matcher:
  min_matches: 15
  verbose: false
  mask: true

mapper:
  name: colmap
  max_num_models: 2
  min_model_size: 3

tracking:
  ckpt_path: src/libs/submodules/cotracker/checkpoints/scaled_offline.pth
  window_len: 15
  grid_size: 60
  sample_ratio: 6
  overlap: 1
