defaults:
  - matcher: tracking

# Assume base_dir includes "1_fixed/images", "2_dynA/images", ...
base_dir: ../sony_ai/20250529/valid/lane/running

# Will be saved in ${out_dir}/${wandb.name}/${wandb.tags}.
out_dir: results
wandb:
  entity: zeki31-global-page
  project: custom_colmap
  group: nvs_12fps
  name: ours_lightglue
  id: null
  mode: offline

retriever:
  img_dir_type: stream # images / frame / stream
  ext: jpg
  start: 0
  duration: -1
  stride: 5

  comp_ratio: 2

mapper:
  name: colmap
  max_num_models: 2
  min_model_size: 3
