base_dir: "../sony_ai/20250529/valid/bench/talking"
output_dir: "results/bench_talking/start=850_fps=12_imgs=120"

retriever:
  img_dir_type: "stream" # images / frame / stream
  ext: "jpg"
  start: 850
  duration: 150
  stride: 5 # 12 fps, total 120 images

keypoint_detector:
  num_features: 4096
  resize_to: 1024

keypoint_matcher:
  min_matches: 15
  verbose: false
  mask: false

colmap_mapper:
  max_num_models: 2
  min_model_size: 3
