base_dir: "../sony_ai/20250529/valid/lane/running"
output_dir: "results/lane_running/start=0_fps=60_imgs=2000_traj"

retriever:
  img_dir_type: "stream" # images / frame / stream
  ext: "jpg"
  start: 0
  duration: -1 # -1 means all
  stride: 1 # 12 fps, total 280 images

  pair_generator: trajectory

keypoint_detector:
  num_features: 4096
  resize_to: 1024

keypoint_matcher:
  min_matches: 15
  verbose: false
  mask: false

mapper:
  name: colmap
  max_num_models: 2
  min_model_size: 3
