base_dir: "../sony_ai/20250529/valid/lane/running"
output_dir: "results/lane_running/start=150_fps=12_imgs=240"

retriever:
  img_dir_type: "stream" # images / frame / stream
  ext: "jpg"
  start: 150
  duration: 450
  stride: 5 # 12 fps, total 280 images

keypoint_detector:
  num_features: 4096
  resize_to: 1024

keypoint_matcher:
  min_matches: 15
  verbose: false
  mask: true

mapper:
  name: colmap
  max_num_models: 2
  min_model_size: 3
