defaults:
  - matcher: tracking

# Assume base_dir includes "1_fixed/images", "2_dynA/images", ...
base_dir: ../sony_ai/20250529/valid/classroom2/talking

# Will be saved in ${out_dir}/${wandb.name}/${wandb.tags}.
out_dir: results
wandb:
  entity: zeki31-global-page
  project: custom_colmap
  group: ours_reset_aliked_full_fps
  name: classroom2_talking
  id: null
  mode: online

train: true
viz: false

retriever:
  img_dir_type: stream # images / frame / stream
  ext: jpg
  start: 0
  duration: -1
  stride: 1

  comp_ratio: 4

mapper:
  name: colmap
  max_num_models: 2
  min_model_size: 3

visualizer:
  name: viser
  filter: false
  resize: 1
  reorient_scene: true
