name: tracking

tracker:
  ckpt_path: src/submodules/cotracker/checkpoints/scaled_offline.pth
  window_len: 10
  grid_size: 60
  sample_ratio: 6
  overlap: 5
  query: aliked
  num_features: 4096
  viz: false

keypoint_detector:
  num_features: 4096

keypoint_matcher:
  pair_generator: view
  min_matches: 15
  verbose: false
  mask: true
